### ISSUE TITLE
Allow field deletion in stages

### ISSUE THREAD

**Issue by laserval** [Findwise/Hydra#74]
It is currently not possible to delete fields from a document.

This could be implemented by having Core not send fields that are null, and add methods for setting fields to null (removing them).

Another possible solution is to extend the stage API to allow deletes, although this might require changing how modification of the stored document is done.

**Comment by rgraneru** [comment]
I have created a stage in hydra-basic-stages that sets an existing field to null. This will at least make sure that the fields aren't sent to solr.

**Comment by jwestberg** [comment]
I suggest that part of the protocol for the `DocumentWriter` is that a document containing a field that is null means that the field should be removed from the database.

This would allow serialization to happen as always between stages and core, with no changes, while allowing fields being removed though _nulling_. One can then easily extend LocalDocument to have methods called `removeContentField(fieldName)` etc that just proxy a call to `putContentField(field, null)`

I would prefer this method since it won't break the API in any meaningful way, and require no migration of pipelines. Unless of course someone, for some unknown reason uses null fields for signaling between stages, but then that's probably a bad design anyway ;)

**Comment by jwestberg** [comment]
As you may have noticed, I used this fix as a guinea pig for automatic closing of issues. 

From this, we can learn that a reference in a _commit_ automatically closes an issue when merged to trunk. Referencing in a pull request doesn't seem to help :) 

Good to know!
